spring.application.name=goal-planner
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/goalplanner
spring.datasource.username=lorenababic
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=YOUR_JWT_SECRET
jwt.expiration=86400000

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini
